config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="hidden lg:block w-full bg-slate-900 py-2 justify-evenly ">
    <div class="place-content-start flex flex-row p-1">
        <div class="text-3xl text-left bg-slate-800 text-white font-black p-2 px-6 rounded-lg">
            <%= link_to "Logo", root_path %>
        </div>
        <div class="flex flex-grow justify-around text-white px-5 self-center font-black rounded-lg">
            <%= link_to "View Posts", posts_path %>
            <%= link_to "New Post", new_post_path %>
        </div>
        <div class="flex flex-grow justify-around bg-slate-100 text-white px-5 self-center font-black rounded-lg">
            <%= link_to "placeholder", posts_path %>
            <%= link_to "placeholder", new_post_path %>
        </div>
    </div>
</nav>

<nav class="lg:hidden w-full bg-slate-900 py-2 justify-evenly" data-controller="toggle">
    <div class="place-content-start flex flex-col p-1">
        <div class="text-3xl text-left bg-slate-800 text-white font-black p-2 px-6 rounded-lg">
            <%= link_to "Logo", root_path %>
            <button data-action="click->toggle#menu" type="button" class="block">
            <i data-toggle-target="hamburger" class="fas fa-bars"></i>
            <i data-toggle-target="close" class="fas fa-times hidden"></i>
            </button>
        </div>
        <div div data-toggle-target="menu" class="hidden">
            <div class="flex flex-col flex-grow justify-around text-white px-5 self-center font-black rounded-lg">
                <%= link_to "View Posts", posts_path %>
                <%= link_to "New Post", new_post_path %>
            </div>
            <div class="flex flex-col flex-grow justify-around bg-slate-100 text-white px-5 self-center font-black rounded-lg">
                <%= link_to "placeholder", posts_path %>
                <%= link_to "placeholder", new_post_path %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="hidden lg:block flex-row w-full max-w-md  bg-slate-800 py-2 justify-evenly">
    <div class="place-content-start flex flex-row">
        <div class="text-4x1 text-left">Teste</div>
        <div class="text-4x1 text-left">Teste 2</div>
        <%= link_to "View Posts", posts_path %>
        <%= link_to "New Post", new_post_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbTop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/3e4b1fee27.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <%= render "layouts/navbar" %>
  </header>
  <body class='flex flex-col h-screen'>
    <p class="notice"> <%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="flex flex-row flex-grow">
      <%= render "layouts/sidebar" %>
        <%= yield %>
    </div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= turbo_frame_tag "new post" do %>
  <%= form_with(model: post, class: "contents") do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="my-5">
      <%= form.label :content %>
      <%= form.text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
  <%= link_to "Cancel", posts_path %>
<% end %>  

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="bg-white px-4 py-0.5 my-1 drop-shadow-sm hover:drop-shadow-2xl duration-300 ease-in-out">
    <div class="my-5 flex flex-row item-start shrink-0">
      <div class="p-4 w-16 h-16 bg-cyan-300 rounded-full">
        <img src="" alt="" class="object-scale-down">
      </div>
      <div class="p-4">
        <%= post.user.name %>
      </div>
    </div>
    <p class="my-5">
      <strong class="block font-medium mb-1">
        <%= post.content %>
      </strong>
    
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">User:</strong>
      
    </p>

    <% if action_name != "show" %>
      <%= link_to "Like", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Comment', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Share', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="flex flex-col w-full items-center bg-slate-700 ">
  <div class="flex flex-col">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex flex-col items-center bg-slate-600 my-5">
      <h1 class="text-teal font-bold text-4xl">Posts</h1>
      <%= turbo_frame_tag "new post" do %>
        <%= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-white text-slate-900 block font-medium" %>
      <% end %>
    </div>

    
    <div id="posts" class="bg-slate-700 pr-96 min-w-full">
      <%= render @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Share a Photo or Video</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>